version: '3.3'
services:
  reminder_system:
    volumes:
      - ./app:/app
    environment:
      - ENV=DEV
      - SWITCH=http://192.168.0.144:51059/reminder_input
    ports:
      - 5050:5050